[settings]
jobs = 1
experimental = true

[env]
CHECKPOINT_DISABLE = "disable"

[tools]
terraform = ["1.8.1", "1.3.2"]
tflint = "latest"
shellcheck = "latest"
markdownlint-cli2 = "latest"
terraform-docs = "latest"

[tasks.pre-commit]
depends = ["fmt:terraform", "generate:module-readme", "generate:example-readme", "lint:tflint", "lint:terraform-validate"]
description = "Run pre-commit tasks"
